appId: com.squer.autotestwithmaestro
tags:
  - weekly
  - deploy
---
#- runFlow: helper/openApp.yml
- runFlow: helper/onboarding-android.yml
- tapOn:
    id: "tab-settings"
- assertVisible: "Settings page"
